# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'editor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for editor
  pod 'iOSPhotoEditor'


end
